### ISSUE TITLE
Getting Error on running on my Local Environment magento v1.9.2

### ISSUE THREAD

**Issue by sethigoldy-zz** [SchumacherFM/Anonygento#4]
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e.anonymized' in 'where clause'' in /Users/zzz/Desktop/magento/lib/Zend/Db/Statement/Pdo.php:228
#0 /Users/zzz/Desktop/magento/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /Users/zzz/Desktop/magento/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /Users/zzz/Desktop/magento/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /Users/zzz/Desktop/magento/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /Users/zzz/Desktop/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#5 /Users/zzz/Desktop/magento/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#6 /Users/zzz/Desktop in /Users/zzz/Desktop/magento/lib/Zend/Db/Statement/Pdo.php on line 235

please help me running this...

**Comment by SchumacherFM** [comment]
You must run this update script: https://github.com/SchumacherFM/Anonygento/blob/master/src%2Fapp%2Fcode%2Fcommunity%2FSchumacherFM%2FAnonygento%2Fsql%2Fschumacherfm_anonygento_setup%2Fmysql4-install-0.0.1.php

Please read the docs on Magento how to apply database updates or how to rerun them by deleting an entry (search for the key anonygento) in core_resource table.

**Comment by sethigoldy-zz** [comment]
Thanks for helping. Now everything is working...
